/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.user;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class CTPN extends javax.swing.JFrame {

    /**
     * Creates new form CTPN
     */
    String url = "jdbc:sqlserver://localhost:1433;databaseName=Database-mẫu";
    String user = "sa", pass = "1", user1 = null;
    Vector nv = null;
    int r = 0, id = 0;
    String c = null, d = null, tt = null, ncc = null, mpn = null;

    public CTPN() {
        initComponents();
    }

    CTPN(String mpn, int mncc) {
        initComponents();
        tab.getSelectionModel()
                .setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tab.getColumnModel().getSelectionModel()
                .setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.ncc = mncc + "";
        this.mpn = mpn;
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btn_xong = new javax.swing.JButton();
        bnt_save = new javax.swing.JButton();
        bnt_xoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        bnt_lammoi = new javax.swing.JButton();
        cbma = new javax.swing.JComboBox<>();
        txt_ten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tên Hàng");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("SỐ LƯỢNG:");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("GIÁ:");

        btn_xong.setBackground(new java.awt.Color(255, 255, 255));
        btn_xong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_xong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close Window_25px.png"))); // NOI18N
        btn_xong.setText("Xong");
        btn_xong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xongActionPerformed(evt);
            }
        });

        bnt_save.setBackground(new java.awt.Color(255, 255, 255));
        bnt_save.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bnt_save.setText("LƯU");
        bnt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_saveActionPerformed(evt);
            }
        });

        bnt_xoa.setBackground(new java.awt.Color(255, 255, 255));
        bnt_xoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bnt_xoa.setText("XÓA");
        bnt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_xoaActionPerformed(evt);
            }
        });

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Hàng", "Số Lương", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Mã Hàng");

        txtgia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtgia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgiaKeyTyped(evt);
            }
        });

        txtsoluong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsoluongKeyTyped(evt);
            }
        });

        bnt_lammoi.setBackground(new java.awt.Color(255, 255, 255));
        bnt_lammoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bnt_lammoi.setText("Làm Mới");
        bnt_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_lammoiActionPerformed(evt);
            }
        });

        cbma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmaItemStateChanged(evt);
            }
        });
        cbma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbmaMouseClicked(evt);
            }
        });

        txt_ten.setText(".............");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnt_lammoi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel27))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btn_xong))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(bnt_save)
                                .addGap(9, 9, 9)
                                .addComponent(bnt_xoa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbma, 0, 180, Short.MAX_VALUE)
                                    .addComponent(txt_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbma)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(bnt_lammoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xong))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnt_save)
                    .addComponent(bnt_xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_saveActionPerformed
        // TODO add your handling code here:
        bnt_xoa.setVisible(true);
        btn_xong.setVisible(true);
//        String kttt = null;
//        if (Integer.parseInt(txtsoluong.getText()) > 0) {
//            kttt = "Còn Hàng";
//        } else {
//            kttt = "Chưa Nhập, đã hết hàng";
//        }
        if (kt()) {
            String sql = " INSERT INTO chi_tiet_pn (MaPN,MaHang,SOLUONG,DONGIA) VALUES(?,?,?,?) "
                    + " update Mat_Hang set SoLuong = ?,DonGia = ?,TinhTrang=? where   MaHang =? ";
            System.out.println(sql);
            Connection con = null;
            PreparedStatement ps = null;
            String a;
            try {
                con = DriverManager.getConnection(url, user, pass);
                ps = con.prepareStatement(sql);
                ps.setString(1, mpn);
                ps.setString(2, cbma.getSelectedItem().toString());
                ps.setString(3, txtsoluong.getText());
                ps.setString(4, txtgia.getText());
                ps.setString(5, txtsoluong.getText());
                ps.setString(6, txtgia.getText());
                ps.setString(7, "1");
                ps.setString(8, cbma.getSelectedItem().toString());
                ps.execute();
                loaddata();
                bnt_save.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Update That Bai!");
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                } catch (SQLException se2) {

                }
                try {
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException se) {
                    se.printStackTrace();
                }
            }

        }

    }//GEN-LAST:event_bnt_saveActionPerformed

    private void bnt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_xoaActionPerformed
        // TODO add your handling code here:
        String sql = "delete from chi_tiet_pn where   MaHang =? ";
        Connection con = null;
        PreparedStatement ps = null;
        try {
            con = DriverManager.getConnection(url, user, pass);
            ps = con.prepareStatement(sql);
            ps.setString(1, cbma.getSelectedItem().toString());
            ps.execute();
            JOptionPane.showMessageDialog(this, "Delete Thanh Cong!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Delete That Bai!");
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
            } catch (SQLException se2) {

            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        loaddata();
    }//GEN-LAST:event_bnt_xoaActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        r = tab.getSelectedRow();
        loadlencompanel(r);
        bnt_save.setEnabled(false);
    }//GEN-LAST:event_tabMouseClicked

    private void bnt_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_lammoiActionPerformed
        bnt_save.setEnabled(true);
        bnt_xoa.setVisible(false);
        btn_xong.setVisible(false);
        txtsoluong.setText("");
        txtgia.setText("");
//        try {
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            Connection con = DriverManager.getConnection(url, user, pass);
//            String sql = "INSERT INTO chi_tiet_pn (SO_PN,MaHang,tenhang,SOLUONG,DONGIA) VALUES('1','"+c+"',null,null,null)";
//            PreparedStatement st = con.prepareStatement(sql);
//            st.executeUpdate();
//            st.close();
//            String sql1 = "  Select top 1 stt from chi_tiet_pn order by stt DESC ";
//            Statement st1 = con.createStatement();
//            ResultSet rs = st1.executeQuery(sql1);
//            while (rs.next()) {
//                id = rs.getInt(1);
//                d = c + id;
//            }
//            lba_ma.setText(d);
//            String sqlup = " update chi_tiet_pn set SO_PN =? , MaHang = ? "
//                    + " where stt =" + id;
//            PreparedStatement stup = con.prepareStatement(sqlup);
//            stup.setString(1, c);
//            stup.setString(2, d);
//            stup.executeUpdate();
//            stup.close();
//            con.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }


    }//GEN-LAST:event_bnt_lammoiActionPerformed

    private void txtsoluongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsoluongKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtsoluongKeyTyped

    private void txtgiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgiaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtgiaKeyTyped

    private void btn_xongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xongActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_xongActionPerformed

    private void cbmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbmaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbmaMouseClicked

    private void cbmaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmaItemStateChanged
        // TODO add your handling code here:
        System.out.println(cbma.getSelectedItem());
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select TenHang from Mat_Hang where MaHang like '" + cbma.getSelectedItem() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txt_ten.setText(rs.getString(1));
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbmaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTPN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_lammoi;
    private javax.swing.JButton bnt_save;
    private javax.swing.JButton bnt_xoa;
    private javax.swing.JButton btn_xong;
    private javax.swing.JComboBox<String> cbma;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab;
    private javax.swing.JLabel txt_ten;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
    //Kiểm Tra txtfield
    private boolean kt() {
        if (txtsoluong.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa Số Lượng", "Error", JOptionPane.ERROR_MESSAGE);
            txtsoluong.requestFocus();
            return false;
        } else if (txtgia.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa Nhập Giá", "Error", JOptionPane.ERROR_MESSAGE);
            txtgia.requestFocus();
            return false;
        }
        return true;
    }

    //load lên bảng dữ liệu
    public void loaddata() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "SELECT  MaHang,SoLuong,DonGia from Mat_Hang where MaNCC like '" + ncc + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nv = new Vector();
                nv.add(rs.getString(1));
                nv.add(rs.getString(2));
                nv.add(rs.getString(3));
                model.addRow(nv);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
//        System.out.println(ncc + 123);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select MaHang from Mat_Hang where MaNCC = '" + ncc + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbma.removeAllItems();
            while (rs.next()) {
                cbma.addItem(rs.getString(1));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadlencompanel(int r) {
        if (r < 0) {
            return;
        }
        cbma.setSelectedItem(tab.getValueAt(r, 0).toString());
        txtsoluong.setText(tab.getValueAt(r, 1).toString());
        txtgia.setText(tab.getValueAt(r, 2).toString());
    }
}
