/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrator
 */
public class HoaDon extends javax.swing.JPanel {

    String url = "jdbc:sqlserver://localhost:1433;databaseName=Database-mẫu";
    String user = "sa", pass = "1", user1 = null, manv = null, makh = null;
    DefaultTableModel model1 = null, model = null;
    Vector nv;
    int tt = 0;

    /**
     * Creates new form HoaDon
     */
    public HoaDon() {
        initComponents();
    }

    HoaDon(String makh, String manv, Vector nv1) {
        initComponents();
        tab.getSelectionModel()
                .setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tab.getColumnModel().getSelectionModel()
                .setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.makh = makh;
        this.manv = manv;
        System.out.println(nv1.size());
        int dem = 0;
        model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        nv = new Vector();
        for (int i = 0; i < nv1.size(); i++) {
            dem++;
            nv.add(nv1.get(i));
            if (dem == 3) {
//                        System.out.println(nv);
                model.addRow(nv);
                dem = 0;
                nv = new Vector();
            }
        }
        lbkh.setText(makh);
        lbnv.setText(manv);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String now = dateFormat.format(date).toString();
        lbngay.setText(now);
        
           for (int j = 0; j < model.getRowCount(); j++) {
                    tt += (Integer.parseInt((String) model.getValueAt(j, 1)));
                 lbtonghoadon.setText(tt+"");
              
             
         }
        capnhat();
    }

    void capnhat() {
        int id1 = 0;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "INSERT INTO Hoa_Don (NgayLap ,MaKH,MaNV)VALUES(null,'" + makh + "','" + manv + "')";
            PreparedStatement st = con.prepareStatement(sql);
            st.executeUpdate();
            st.close();
            String sql1 = "  Select top 1 MaHD from Hoa_Don order by MaHD DESC ";
            Statement st1 = con.createStatement();
            ResultSet rs = st1.executeQuery(sql1);
            while (rs.next()) {
                id1 = rs.getInt(1);
            }
            lbmhd.setText(id1 + "");
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbmhd = new javax.swing.JLabel();
        lbngay = new javax.swing.JLabel();
        lbkh = new javax.swing.JLabel();
        lbtonghoadon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbnv = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Mã Hóa Đơn");

        jLabel2.setText("Ngày Lập");

        jLabel3.setText("Tổng Thành Tiền");

        jLabel4.setText("Mã Khách Hàng");

        lbmhd.setText("........................");

        lbngay.setText("........................");

        lbkh.setText("........................");

        lbtonghoadon.setText("........................");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Hàng", "Đơn Giá", "Số Lượng"
            }
        ));
        jScrollPane1.setViewportView(tab);

        jButton1.setText("Xác Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã Nhân Viên");

        lbnv.setText("........................");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbtonghoadon)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbnv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmhd)
                            .addComponent(lbkh)
                            .addComponent(lbngay))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmhd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbngay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbkh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbnv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbtonghoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean kthd = true;
        int i = 0;
        //Nhập lên cơ sở dữ liệu
        String sql = "Update Hoa_Don set NgayLap=? where MaHD like '" + lbmhd.getText() + "'";
//        System.out.println(sql);
        Connection con = null;
        PreparedStatement ps = null;
        String a;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String now = dateFormat.format(date).toString();
        try {
            con = DriverManager.getConnection(url, user, pass);
            ps = con.prepareStatement(sql);
            ps.setString(1, now);
            ps.execute();
            JOptionPane.showMessageDialog(this, "Insert Thanh Cong!");
            kthd = true;
        } catch (Exception e) {
            kthd = false;
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Insert That Bai!");
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
            } catch (SQLException se2) {

            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }

        if (kthd) {
            for (i = 0; i < model.getRowCount(); i++) {
                String ams = null;
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection con1 = DriverManager.getConnection(url, user, pass);

                    String sql1 = "select MaHang from Mat_Hang where TenHang like '" + model.getValueAt(i, 0) + "'";
                    Statement st = con1.createStatement();
                    ResultSet rs = st.executeQuery(sql1);
                    while (rs.next()) {
                        ams = rs.getString(1);
                    }
                    System.out.println(ams + "123");

                } catch (Exception e) {
                    System.out.println(e);
                    System.out.println("that bai");
                }

                String sql2 = " INSERT INTO Chi_Tiet_Hoa_Don (MaHD,MaHang,SoLuong) VALUES(?,?,?) ";
                Connection con2 = null;
                PreparedStatement ps2 = null;
                try {
                    con2 = DriverManager.getConnection(url, user, pass);
                    ps2 = con2.prepareStatement(sql2);
                    ps2.setString(1, lbmhd.getText());
                    ps2.setString(2, ams);
                    ps2.setString(3, model.getValueAt(i, 2) + "");
                    ps2.execute();
                    kthd = true;
                } catch (Exception e) {
                    kthd = false;
                    e.printStackTrace();
                    break;
                } finally {
                    try {
                        if (ps2 != null) {
                            ps2.close();
                        }
                    } catch (SQLException se2) {

                    }
                    try {
                        if (con2 != null) {
                            con2.close();
                        }
                    } catch (SQLException se) {
                        se.printStackTrace();
                    }
                }
            }
        }

        if (kthd) {
            System.setProperty("java.awt.headless", "true");
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con2 = DriverManager.getConnection(url, user, pass);
                Hashtable hash = new Hashtable();
                hash.put("mahoadon", lbmhd.getText() + "");
//            System.out.println(hash+"");
                JasperPrint print = JasperFillManager.fillReport(getClass().getResource("/panel/hoadondemo.jasper").toURI().getPath(), hash, con2);
                JasperViewer jv = new JasperViewer(print, false);
                jv.setVisible(true);
                JasperExportManager.exportReportToPdfFile(print, "HoaDon"+lbmhd.getText()+".pdf");
            } catch (Exception ex) {
                System.out.println(ex);

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbkh;
    private javax.swing.JLabel lbmhd;
    private javax.swing.JLabel lbngay;
    private javax.swing.JLabel lbnv;
    private javax.swing.JLabel lbtonghoadon;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
