/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.LOGIN;
import javaapplication1.user;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class matkhau extends javax.swing.JFrame {

    /**
     * Creates new form matkhau
     */
    // thiết lập đường dẫn database
    String user1 = "";//Lấy username toàn cục
    String url = "jdbc:sqlserver://localhost:1433;databaseName=Database-mẫu";
    String user = "sa", pass = "1";
    
    public matkhau() {
        initComponents();
    }
    
    //Nếu có đối số truyền vào
    matkhau(String user1) {
        initComponents();
        this.user1 = user1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_mkc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_mkms = new javax.swing.JTextField();
        txt_check = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbcu = new javax.swing.JLabel();
        lbcheck = new javax.swing.JLabel();
        lbms = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mật khẩu cũ: ");

        txt_mkc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_mkc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_mkcKeyReleased(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mật khẩu mới: ");

        txt_mkms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_mkms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_mkmsKeyReleased(evt);
            }
        });

        txt_check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_check.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_checkKeyReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nhập lại:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbmsKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_check, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_mkms, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(txt_mkc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbcheck, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbms, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbcu))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_mkc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mkms, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbms))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_check, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String sql = " update Nhan_Vien set MatKhau = ? where  username = '" + user1 + "' ";
        Connection con = null;
        PreparedStatement ps = null;
        try {
            con = DriverManager.getConnection(url, user, pass);
            ps = con.prepareStatement(sql);
            ps.setString(1, txt_check.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "Sửa Thành Công!");
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
            } catch (SQLException se2) {
                
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }

        //Cập Nhật tình trạng
        String sql2 = " update Nhan_Vien set TinhTrang = ? where  username = '" + user1 + "'";
//        System.out.println(user + "123" + sql2);
        Connection con1 = null;
        PreparedStatement ps1 = null;
        try {
            con1 = DriverManager.getConnection(url, user, pass);
            ps1 = con1.prepareStatement(sql2);
            ps1.setString(1, "0");
            ps1.execute();
//            System.out.println("đã sửa thành công, và offline");
//            user dong = null;
//           dong.dispatchEvent(new WindowEvent(dong, WindowEvent.WINDOW_CLOSING));
            LOGIN lg = new LOGIN();
            lg.setVisible(true);
            dispose();
            
        } catch (Exception e) {
            e.printStackTrace();
            
        } finally {
            if (ps1 != null) {
                try {
                    ps1.close();
                } catch (SQLException ex) {
                    Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_mkcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mkcKeyReleased
        //Sử dụng sự kiện thả phím để bắt lỗi mật khẩu cũ có đúng không
        try {
            // TODO add your handling code here:
            //Kết nối database
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            //Select MatKhau có trên database không
            String sql = "select MatKhau from Nhan_Vien where  username = '" + user1 + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                if (txt_mkc.getText().equals(rs.getString("MatKhau"))) {
                    txt_mkc.setForeground(new java.awt.Color(0, 51, 255));
                    txt_mkc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
                    lbcu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/confirm.png")));
                } else {
                    txt_mkc.setForeground(new java.awt.Color(255, 0, 0));
                    txt_mkc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
                    lbcu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close-cross-circular-interface-button.png")));
                }
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txt_mkcKeyReleased

    private void lbmsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbmsKeyReleased
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sai Mật Khẩu", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_lbmsKeyReleased
    

    private void txt_mkmsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mkmsKeyReleased
        // TODO add your handling code here:
        boolean kttext = true;
        char c = evt.getKeyChar();
        char[] SPECIAL_CHARACTERS = {' ', '!', '"', '#', '$', '%',
            '*', '+', ',', ':', '<', '=', '>', '?', '@', '[', '\\', ']', '^',
            '`', '|', '~',};
        for (char a : SPECIAL_CHARACTERS) {
            if (c == a) {
                kttext = false;
            }
        }
        
        if (kttext) {
            evt.consume();
            if (txt_mkms.getText().length() > 5) {
                txt_mkms.setForeground(new java.awt.Color(0, 51, 255));
                txt_mkms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
                lbms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/confirm.png")));
            } else {
                txt_mkms.setForeground(new java.awt.Color(255, 153, 0));
                txt_mkms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
                lbms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exclamation-mark.png")));
            }
        } else {
//            txt_mkms.setText(txt_mkms.getText().substring(0, txt_mkms.getText().length()-1));
            txt_mkms.setText(txt_mkms.getText().replace(c + "", ""));
            txt_mkms.requestFocus();
        }
    }//GEN-LAST:event_txt_mkmsKeyReleased

    private void txt_checkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_checkKeyReleased
        // TODO add your handling code here:
        if (txt_check.getText().equals(txt_mkms.getText())) {
            txt_check.setForeground(new java.awt.Color(0, 51, 255));
            txt_check.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
            lbcheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/confirm.png")));
        } else {
            txt_check.setForeground(new java.awt.Color(255, 0, 0));
            txt_check.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            lbcheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close-cross-circular-interface-button.png")));
            txt_check.requestFocus();
        }
    }//GEN-LAST:event_txt_checkKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matkhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbcheck;
    private javax.swing.JLabel lbcu;
    private javax.swing.JLabel lbms;
    private javax.swing.JTextField txt_check;
    private javax.swing.JTextField txt_mkc;
    private javax.swing.JTextField txt_mkms;
    // End of variables declaration//GEN-END:variables
}
