package panel;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javaapplication1.user;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Duy
 */
public class phieunhap extends javax.swing.JPanel {

    String url = "jdbc:sqlserver://localhost:1433;databaseName=Database-mẫu";
    String user = "sa", pass = "1";
    File file = null;
    Vector nv = null;
    int r = 0, id = 0, mancc = 0;
    String c = null, user1 = null, tt = null, manv = "", mpn = "";
    qlhhPanel ncc;
    GridBagLayout layout = new GridBagLayout();

    /**
     * Creates new form NewJPanel
     */
    public phieunhap() {
        initComponents();
        loaddata();
        loadlencompanel(r);
        bnt_themhang.setVisible(false);
        bnt_xem.setVisible(false);
    }

    public phieunhap(String user2, String trangthai) {
        initComponents();
        loaddata();
        tab.getSelectionModel()
                .setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tab.getColumnModel().getSelectionModel()
                .setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        try {
            loadlencompanel(r);
        } catch (Exception e) {

        }
        this.user1 = user2;
        this.tt = trangthai;
        bnt_themhang.setVisible(false);
        bnt_xem.setVisible(false);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select MaNV from Nhan_Vien where  username like '" + user1 + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                manv = rs.getString("MaNCC") + "";
                lbht.setText(manv);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void loaddata() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = " SELECT MaPN,NgayNhap,Phieu_Nhap_Hang.MaNCC,MaNV,TenNCC from Phieu_Nhap_Hang inner join Nha_Cung_Cap on Phieu_Nhap_Hang.MaNCC = Nha_Cung_Cap.MaNCC ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nv = new Vector();
                nv.add(rs.getString(1));
                nv.add(rs.getString(2));
                nv.add(rs.getString(3));
                nv.add(rs.getString(4));
                nv.add(rs.getString(5));
                model.addRow(nv);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select TenNCC from Nha_Cung_Cap";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbocc.removeAllItems();
            while (rs.next()) {
                cbocc.addItem(rs.getString(1));
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void loadlencompanel(int r) {
        if (r < 0) {
            return;
        }
        lbht2.setText(tab.getValueAt(r, 0).toString());
        lbht1.setText(tab.getValueAt(r, 1).toString());
        cbocc.setSelectedItem(tab.getValueAt(r, 4));
        lbht.setText(tab.getValueAt(r, 3).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTaskButtonBeanInfo1 = new id.web.martinusadyh.button.MTaskButtonBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        bnt_luu = new javax.swing.JButton();
        bnt_themhang = new javax.swing.JButton();
        cbocc = new javax.swing.JComboBox<>();
        lbht = new javax.swing.JLabel();
        lbht1 = new javax.swing.JLabel();
        lbht2 = new javax.swing.JLabel();
        bnt_xem = new javax.swing.JButton();
        bntdelete1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Số PN");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ngày nhập :");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã nhà cung cấp :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên :");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số Phiếu Nhập", "Ngày nhập", "Mã NCC", "Mã nhân viên", "NhaNCC"
            }
        ));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(4).setMinWidth(0);
            tab.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bnt_luu.setBackground(new java.awt.Color(255, 255, 255));
        bnt_luu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_luu.setText("Lưu");
        bnt_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_luuActionPerformed(evt);
            }
        });

        bnt_themhang.setText("thêm hàng");
        bnt_themhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_themhangActionPerformed(evt);
            }
        });

        cbocc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbocc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboccItemStateChanged(evt);
            }
        });
        cbocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboccActionPerformed(evt);
            }
        });

        lbht.setText(".................");

        lbht1.setText(".................");

        lbht2.setText(".................");

        bnt_xem.setText("Xem Hàng");

        bntdelete1.setBackground(new java.awt.Color(255, 255, 255));
        bntdelete1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntdelete1.setText("Kết Thúc");
        bntdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(bntdelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bnt_themhang)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bnt_xem)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addGap(75, 75, 75)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbocc, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbht, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbht1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbht2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bnt_luu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(bntdelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bnt_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbht2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbht1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bnt_themhang)
                                        .addComponent(bnt_xem))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbocc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbht, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboccActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboccActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//Date date = new Date();
//System.out.println(dateFormat.format(date));
//        System.out.println(dateFormat.format(date).replace("-", ""));
        bnt_themhang.setVisible(false);
        bnt_xem.setVisible(false);
        bnt_luu.setVisible(true);
        tab.setVisible(false);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "INSERT INTO Phieu_Nhap_Hang (NgayNhap,MaNCC,MaNV) VALUES(null,'1',null)";
            PreparedStatement st = con.prepareStatement(sql);
            st.executeUpdate();
            st.close();
            String sql1 = "  Select top 1 MaPN from Phieu_Nhap_Hang order by MaPN DESC ";
            Statement st1 = con.createStatement();
            ResultSet rs = st1.executeQuery(sql1);
            while (rs.next()) {
                id = rs.getInt(1);
            }
            lbht2.setText(id + "");
            mpn = id + "";
            lbht1.setText(dateFormat.format(date) + "");
            JOptionPane.showMessageDialog(this, "Updata successfull");
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void bnt_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_luuActionPerformed
        // TODO add your handling code here:

        System.out.println(cbocc.getSelectedItem().toString());

        bnt_themhang.setVisible(true);
        bnt_xem.setVisible(false);
        tab.setVisible(true);
        String sql = " update Phieu_Nhap_Hang set NgayNhap = ?,MaNCC = ?,MaNV = ?  where   MaPN =? ";

        Connection con = null;
        PreparedStatement ps = null;
        String a;
//        System.out.println(cbocc.getSelectedItem());
        try {
            con = DriverManager.getConnection(url, user, pass);
            ps = con.prepareStatement(sql);
            ps.setString(1, lbht1.getText());
            ps.setInt(2, mancc);
            ps.setString(3, lbht.getText());
            ps.setString(4, lbht2.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "Update Thanh Cong!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Update That Bai!");
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
            } catch (SQLException se2) {

            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        loaddata();
    }//GEN-LAST:event_bnt_luuActionPerformed

    private void bnt_themhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_themhangActionPerformed
        // TODO add your handling code here:
        System.out.println(cbocc.getSelectedItem().toString());
        CTPN a = new CTPN(mpn, mancc);
        a.setVisible(true);

    }//GEN-LAST:event_bnt_themhangActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        bnt_themhang.setVisible(true);
        bnt_xem.setVisible(true);
        bnt_luu.setVisible(false);
        r = tab.getSelectedRow();
        loadlencompanel(r);
    }//GEN-LAST:event_tabMouseClicked

    private void bntdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdelete1ActionPerformed
        // TODO add your handling code here:
        ncc = new qlhhPanel();
        setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        add(ncc, c);
        jPanel1.setVisible(false);
        ncc.setVisible(true);

    }//GEN-LAST:event_bntdelete1ActionPerformed

    private void cboccItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboccItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, user, pass);
            System.out.println(cbocc.getSelectedItem().toString());
            String sql = " select MaNCC from Nha_Cung_Cap where  TenNCC like N'" + cbocc.getSelectedItem().toString() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                System.out.println(rs.getString(1));
                mancc = rs.getInt(1);
            }
            System.out.println(mancc);
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        c = mancc + "";
        System.out.println(mancc);
    }//GEN-LAST:event_cboccItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_luu;
    private javax.swing.JButton bnt_themhang;
    private javax.swing.JButton bnt_xem;
    private javax.swing.JButton bntdelete1;
    private javax.swing.JComboBox<String> cbocc;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbht;
    private javax.swing.JLabel lbht1;
    private javax.swing.JLabel lbht2;
    private id.web.martinusadyh.button.MTaskButtonBeanInfo mTaskButtonBeanInfo1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
