/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import thongke.mathang;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import panel.giohangPanel;
import panel.nhacungcap_1;
import panel.phieunhap;
import panel.qlhhPanel;
import panel.qlnv;

import panel.tk;
import panel.tt;

/**
 *
 * @author Duy
 */
public class user extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    tt tt1;
    qlnv qlnv;
    qlhhPanel qlhh;
    giohangPanel gh;
    tk tk1;
    mathang cong;
    int xMouse;
    int yMouse;
    String user = null;
    String url = "jdbc:sqlserver://localhost:1433;databaseName=Database-mẫu";
    String user1 = "sa", pass = "1";
    boolean kticon = true;
    String roles = null;
    /**
     * Creates new form user
     */
    private boolean dem = true;

    public user() throws ParseException {
        initComponents();
//        tt1 = new tt();
//        qlnv = new qlnv();
//        qlhh = new qlhhPanel();
//        gh = new giohangPanel();
//        tk1 = new tk();
//        ncc = new nhacungcap_1();
//        pn = new phieunhap();
//        jPanel5.setLayout(layout);
//        GridBagConstraints c = new GridBagConstraints();
//        c.gridx = 0;
//        c.gridy = 0;
//        jPanel5.add(tt1, c);
//        jPanel5.add(qlnv, c);
//        jPanel5.add(qlhh, c);
//        jPanel5.add(gh, c);
//        jPanel5.add(tk1, c);
//        jPanel5.add(ncc, c);
//        jPanel5.add(pn, c);
//        tt1.setVisible(true);
//        qlnv.setVisible(false);
//        qlhh.setVisible(false);
//        gh.setVisible(false);
//        tk1.setVisible(false);
//        ncc.setVisible(false);
//        pn.setVisible(false);

    }

    public user(String user, String trangthai, String manv, String role) throws ParseException {
        initComponents();
        // tạo mới nhưng jpane cần hiển thị
        tt1 = new tt(user, trangthai);//Jpane Thông Tin
        qlnv = new qlnv(manv,role);//Jpane quản lý nhân viên
        qlhh = new qlhhPanel(user);//Jpane quản lý hàng hóa
        gh = new giohangPanel(user);//Jpane giỏ hàng
        tk1 = new tk();//Jpane Thống kê
        cong = new mathang();
        jPanel5.setLayout(layout);//nơi chuyển cái jpane
        GridBagConstraints c = new GridBagConstraints();
//            c.gridy++;
//            c.gridx++;
//            c.weightx = 0.5;
//    c.weighty = 0.1;
//    c.gridx = 100;
//    c.gridy = 100;
//    
//c.fill = GridBagConstraints.BOTH;

        c.gridx = 1;
        c.gridy = 1;
        //Add tất cả các jpane vô jpanel5
        jPanel5.add(tt1, c);
        jPanel5.add(qlnv, c);
        jPanel5.add(qlhh, c);
        jPanel5.add(gh, c);
        jPanel5.add(tk1, c);
        //setVisible cần hiện thị
        tt1.setVisible(true);
        qlnv.setVisible(false);
        qlhh.setVisible(false);
        gh.setVisible(false);
        tk1.setVisible(false);
        this.user = user;
        //Dán Tên lbusername
        lbusername.setText(user);
        this.roles = role;
        System.out.println(roles + "chức vụ");

    }

//    public void removeMinMaxClose(Component comp) {
//        if (comp instanceof AbstractButton) {
//            comp.getParent().remove(comp);
//        }
//        if (comp instanceof Container) {
//            Component[] comps = ((Container) comp).getComponents();
//            for (int x = 0, y = comps.length; x < y; x++) {
//                removeMinMaxClose(comps[x]);
//            }
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbusername = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(BorderFactory.createMatteBorder(1, 0,0, 1,Color.DARK_GRAY));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Minimize Window_32px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Maximize Window_32px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close Window_32px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
            .addComponent(jSeparator2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbusername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbusername.setForeground(new java.awt.Color(255, 255, 255));
        lbusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Businessman_25px.png"))); // NOI18N
        lbusername.setText("USER");
        jPanel4.add(lbusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new java.awt.GridLayout(10, 1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thông tin");
        jLabel5.setBorder(BorderFactory.createMatteBorder(0,  0, 1, 0,Color.WHITE));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QL Nhân Viên");
        jLabel6.setBorder(BorderFactory.createMatteBorder(0,  0, 1, 0,Color.WHITE));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("QL Hàng Hóa");
        jLabel7.setBorder(BorderFactory.createMatteBorder(0,  0, 1, 0,Color.WHITE));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel7);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thống Kê");
        jLabel9.setBorder(BorderFactory.createMatteBorder(0,  0, 1, 0,Color.WHITE));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel9);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Giỏ Hàng");
        jLabel14.setBorder(BorderFactory.createMatteBorder(0,  0, 1, 0,Color.WHITE));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel14);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel8);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel10);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel11);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/18136045_1146084775536790_1840619911_n.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(BorderFactory.createMatteBorder(0, 0,1, 1,Color.DARK_GRAY));
        jPanel5.setPreferredSize(new java.awt.Dimension(711, 803));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Phần Hiện Thị của jpane thống kê---------------------------------------
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (roles.equals("0") || roles.equals("1")) {
            jLabel9.setEnabled(true);
            jLabel9.setBackground(new Color(0, 102, 153));
            jLabel9.setOpaque(true);
            //Phần Giao Diện
            jLabel9.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.ORANGE));
            jLabel5.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel6.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel7.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel14.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel6.setBackground(new Color(0, 102, 102));
            jLabel5.setBackground(new Color(0, 102, 102));
            jLabel7.setBackground(new Color(0, 102, 102));
            jLabel14.setBackground(new Color(0, 102, 102));
            //Phần Hiện Thị của jpane thông tin
            tt1.setVisible(false);
            qlnv.setVisible(false);
            qlhh.setVisible(false);
            gh.setVisible(false);
            tk1.setVisible(true);
            cong.setVisible(true);

        }
    }//GEN-LAST:event_jLabel9MouseClicked

    //Phần Hiện Thị của jpane quản lý hàng hóa---------------------------------------
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (roles.equals("1")) {
            jLabel7.setBackground(new Color(0, 102, 153));
            jLabel7.setOpaque(true);
            jLabel7.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.ORANGE));
            jLabel5.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel6.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel9.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel14.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel6.setBackground(new Color(0, 102, 102));
            jLabel5.setBackground(new Color(0, 102, 102));
            jLabel9.setBackground(new Color(0, 102, 102));
            jLabel14.setBackground(new Color(0, 102, 102));
            tt1.setVisible(false);
            qlnv.setVisible(false);
            qlhh.setVisible(true);
            gh.setVisible(false);
            tk1.setVisible(false);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    //Phần Hiện Thị của jpane quản lý nhân viên---------------------------------------
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if (roles.equals("1")) {
            jLabel6.setBackground(new Color(0, 102, 153));
            jLabel6.setOpaque(true);
            jLabel6.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.ORANGE));
            jLabel5.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel7.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel9.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel14.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel7.setBackground(new Color(0, 102, 102));
            jLabel5.setBackground(new Color(0, 102, 102));
            jLabel9.setBackground(new Color(0, 102, 102));
            jLabel14.setBackground(new Color(0, 102, 102));
            tt1.setVisible(false);
            qlnv.setVisible(true);
            qlhh.setVisible(false);
            gh.setVisible(false);
            tk1.setVisible(false);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    //Phần Hiện Thị của jpane  thông tin---------------------------------------
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jLabel5.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.ORANGE));
        jLabel6.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
        jLabel7.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
        jLabel9.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
        jLabel14.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
        jLabel5.setBackground(new Color(0, 102, 153));
        jLabel5.setOpaque(true);
        jLabel6.setBackground(new Color(0, 102, 102));
        jLabel7.setBackground(new Color(0, 102, 102));
        jLabel9.setBackground(new Color(0, 102, 102));
        jLabel14.setBackground(new Color(0, 102, 102));
        tt1.setVisible(true);
        qlnv.setVisible(false);
        qlhh.setVisible(false);
        gh.setVisible(false);
        tk1.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        if (kticon) {
            setExtendedState(MAXIMIZED_BOTH);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Maximize Window_32px.png")));

            kticon = false;
        } else {
            setExtendedState(NORMAL);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Restore Window_32px.png")));
            kticon = true;
        }
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        String sql2 = " update Nhan_Vien set TinhTrang = ? where  username = '" + user + "'";
        //        System.out.println(user + "123" + sql2);
        Connection con1 = null;
        PreparedStatement ps1 = null;
        try {
            con1 = DriverManager.getConnection(url, user1, pass);
            ps1 = con1.prepareStatement(sql2);
            ps1.setString(1, "0");
            ps1.execute();
            //            System.out.println("đã sửa thành công, và offline");
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace();

        } finally {
            if (ps1 != null) {
                try {
                    ps1.close();
                } catch (SQLException ex) {
                    Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        //Cập Nhật tình trạng
        String sql2 = " update Nhan_Vien set TinhTrang = ? where  username = '" + user + "'";
//        System.out.println(user + "123" + sql2);
        Connection con1 = null;
        PreparedStatement ps1 = null;
        try {
            con1 = DriverManager.getConnection(url, user1, pass);
            ps1 = con1.prepareStatement(sql2);
            ps1.setString(1, "0");
            ps1.execute();
//            System.out.println("đã sửa thành công, và offline");
//            user dong = null;
//           dong.dispatchEvent(new WindowEvent(dong, WindowEvent.WINDOW_CLOSING));
            LOGIN lg = new LOGIN();
            lg.setVisible(true);
            dispose();

        } catch (Exception e) {
            e.printStackTrace();

        } finally {
            if (ps1 != null) {
                try {
                    ps1.close();
                } catch (SQLException ex) {
                    Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        if (roles.equals("2") || roles.equals("1")) {
           jLabel14.setBackground(new Color(0, 102, 153));
            jLabel14.setOpaque(true);
            jLabel14.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.ORANGE));
            jLabel5.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel6.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel9.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel7.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.WHITE));
            jLabel6.setBackground(new Color(0, 102, 102));
            jLabel5.setBackground(new Color(0, 102, 102));
            jLabel9.setBackground(new Color(0, 102, 102));
            jLabel7.setBackground(new Color(0, 102, 102));
            //Phần Hiện Thị của jpane thông tin
            tt1.setVisible(false);
            qlnv.setVisible(false);
            qlhh.setVisible(false);
            gh.setVisible(true);
            tk1.setVisible(false);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new user().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbusername;
    // End of variables declaration//GEN-END:variables
}
